#!/usr/bin/env python3

print("=== DEBUG PRINTS ADDED TO BOOKING ENDPOINT ===")
print("✅ Added the 3 requested debug prints to /appointments/book")
print("")
print("ADDED DEBUG PRINTS:")
print("")
print("1. ✅ print('----- BOOKING DEBUG -----')")
print("2. ✅ print('REQUEST:', booking_data.dict())")
print("3. ✅ hospital_service = (")
print("       db.query(HospitalService)")
print("       .filter(HospitalService.id == booking_data.hospital_service_id)")
print("       .first()")
print("   )")
print("4. ✅ print('FOUND SERVICE:', hospital_service)")
print("5. ✅ print('-------------------------')")
print("")
print("ENDPOINT STRUCTURE:")
print("@router.post('/book')")
print("def book_appointment(")
print("    booking_data: BookingRequest,")
print("    request: Request,  # Added Request parameter")
print("    db: Session = Depends(get_db)")
print("):")
print("")
print("EXPECTED BACKEND OUTPUT WHEN BOOKING:")
print("----- BOOKING DEBUG -----")
print("REQUEST: {")
print("    'hospital_service_id': UUID('123e4567-e89b-12d3-a456-426614174000'),")
print("    'appointment_date': datetime.date(2026, 3, 6),")
print("    'patient_name': 'John Doe',")
print("    'patient_phone': '9876543210'")
print("}")
print("FOUND SERVICE: <HospitalService object at 0x...>")
print("-------------------------")
print("BOOKING REQUEST:")
print("  hospital_service_id: 123e4567-e89b-12d3-a456-426614174000")
print("  appointment_date: 2026-03-06")
print("  patient_name: John Doe")
print("  patient_phone: 9876543210")
print("  hospital_service_id type: <class 'uuid.UUID'>")
print("Hospital service found: True")
print("Hospital service details: ID=123e4567..., Service=Cardiology")
print("")
print("DEBUGGING BENEFITS:")
print("✅ Shows complete request payload structure")
print("✅ Displays hospital_service_id as UUID object")
print("✅ Shows if service was found in database")
print("✅ Provides clear visual separation with dashes")
print("✅ Maintains existing debug logging for compatibility")
print("")
print("HOW TO TEST:")
print("1. Backend server should auto-reload with changes")
print("2. Go to patient booking page")
print("3. Fill out booking form")
print("4. Click 'Confirm Booking'")
print("5. Check backend console for debug output")
print("6. Should see the 5 debug print lines")
print("")
print("TROUBLESHOOTING:")
print("If 'FOUND SERVICE: None':")
print("- Check if hospital_service_id matches database")
print("- Verify service exists in HospitalService table")
print("- Check UUID format and validity")
print("")
print("If 'REQUEST:' shows empty or wrong data:")
print("- Check frontend payload structure")
print("- Verify JSON body is being sent correctly")
print("- Check Content-Type header is application/json")
print("")
print("SUCCESS INDICATORS:")
print("✅ Debug prints appear in backend console")
print("✅ REQUEST shows complete booking data")
print("✅ FOUND SERVICE shows service object (not None)")
print("✅ Booking proceeds successfully")
print("✅ No 'Hospital service not found' error")
