"""add_established_year_column

Revision ID: 52e51c2087c5
Revises: 001_update_models
Create Date: 2026-02-28 18:37:13.739779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e51c2087c5'
down_revision = '001_update_models'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('established_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'established_year')
    # ### end Alembic commands ###
