"""add_staff_id_to_staff_table

Revision ID: f1fbb81158aa
Revises: 52e51c2087c5
Create Date: 2026-02-28 18:57:19.762020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fbb81158aa'
down_revision = '52e51c2087c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('staff_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_column('staff', 'staff_id')
    # ### end Alembic commands ###
